dist: bionic

language: haskell
ghc: 8.2

cache:
 directories:
 - $HOME/.cabal/packages
 - $HOME/.cabal/store
 - $HOME/.cabal/bin

before_install:
  - cabal install --only-dependencies idris-1.3.2

install:
  - make idris2
  - make libs

script: make test
