dist: bionic
sudo: required
addons:
  apt:
    packages:
      - clang
      - lld-6.0
      - chicken-bin
      - racket
      - libx11-dev
      - uuid-dev
      - libncurses5-dev

language: haskell
ghc: 8.2

env:
  - IDRIS_CC=clang

before_install:
  - wget https://github.com/cisco/ChezScheme/archive/v9.5.2.tar.gz
  - tar xzf v9.5.2.tar.gz && cd ChezScheme-9.5.2
  - ./configure --threads && sudo make -j install
  - cd ..

install:
  - export PATH=$HOME/.cabal/bin:$PATH
  - cabal update
  - travis_wait 20 cabal install -j --with-ld=ld.lld idris-1.3.2

script:
  - travis_wait 20 make idris2
  - make libs
  - make test
