dist: bionic

language: haskell
ghc: 8.2

cache:
 directories:
 - $HOME/.cabal/packages
 - $HOME/.cabal/store
 - $HOME/.cabal/bin

before_install:
  - travis_wait 20 cabal install idris-1.3.2
  - apt-get update -y
  - apt-get install -y curl wget chicken-bin racket libx11-dev uuid-dev clang
  - wget https://github.com/cisco/ChezScheme/archive/v9.5.2.tar.gz
  - tar xvzf v9.5.2.tar.gz && cd ChezScheme-9.5.2
  - ./configure --threads && make -j install

install:
  - export IDRIS_CC=clang
  - make idris2
  - make libs

script: make test
