dist: bionic
addons:
  apt:
    packages:
      - clang
      - lld-6.0
      - chicken-bin
      - racket
      - libx11-dev
      - uuid-dev
      - libncurses5-dev

services:
  - docker

language: haskell
ghc: 8.2

env:
  - IDRIS_CC=clang

before_install:
  # - wget https://github.com/cisco/ChezScheme/archive/v9.5.2.tar.gz
  # - tar xvzf v9.5.2.tar.gz && cd ChezScheme-9.5.2
  # - ./configure --threads && sudo make -j install
  # - cd ..

install:
  # - docker run --rm --entrypoint tar "theodus/idris:1.3.2" cf - /root/.cabal >cabal_stuff.tar
  # - tar xvf cabal_stuff.tar
  # - cp -r root/.cabal/* $HOME/.cabal
  # - ls $HOME/.cabal/share/x86_64-linux-ghc-8.2.2/idris-1.3.2/libs

  - export PATH=$HOME/.cabal/bin:$PATH
  - cabal update && cabal install -j --with-ld=ld.lld idris-1.3.2

script:
  - travis_wait 20 make idris2
  - make libs
  - make test
